<?php
/**
  * Implements hook_menu(). 
  */
function internet_lobby_menu() {
  $items['internet-lobby-page'] = array (
    'title' => 'Internet lobby',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('internet_lobby_page_form'),
    'access callback' => TRUE,
  );
  return $items;
}

/**
  * Build lobby form.
  */
function internet_lobby_page_form($form, $form_state) {
  $form['surname'] = array (
    '#type' => 'textfield',
    '#title' => t('Surname'),
    '#required' => TRUE,
  );
  $form['name'] = array (
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#required' => TRUE,
  );
  $form['secondname'] = array (
    '#type' => 'textfield',
    '#title' => t('Second name'),
    '#required' => TRUE,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('E-mail'),
    '#required'  => TRUE,
  );
  $form['age'] = array(
    '#type' => 'textfield',
    '#title' => t('Age'),
    '#size' => 3,
    '#maxlength' => 3,
    '#required' => TRUE,
  );
  $form['theme'] = array (
    '#type' => 'textfield',
    '#title' => t('Theme'),
    '#required' => TRUE,
  );
  $form['message'] = array (
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#required' => TRUE,
  );
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => t('Send'),
    '#required' => TRUE,
  );
  return $form;
}

/**
  * Validate function for internet_lobby_page_form. 
  */ 
function internet_lobby_page_form_validate($form, &$form_state) { 
  if (($form_state['values']['age'] <= 0) || (!is_numeric($form_state['values']['age']))) {
    form_set_error('age', t('Enter the correct age'));
  }
} 

/**
  * Submit function for internet_lobby_page_form.
  */
function internet_lobby_page_form_submit($form, &$form_state) {
  $mail = drupal_mail('internet_lobby', 'key', "admin@example.com", language_default(), $form_state['values']);
  if ($mail['result']) {    
    drupal_set_message(t('Message sent')); 
  } 
  else { 
    drupal_set_message(t("Unforunately, message wasn't sent")); 
  } 
}

/**
  * Implements hook_mail()
  */
function internet_lobby_mail($key, &$message, $params) {
  if ($key == 'key') {
    $message['subject'] = $params['theme'];
    $message['body'][] = $params['message'] . "\n" . $params['surname'] . " " . $params['name'] . " " . $params['secondname'] . ", " . $params['age'] . ", " . $params['email'];
  }
}